all:
	g++ sender_sigalrm.cpp -o sender_sigalrm
	g++ sender_select.cpp -o sender_select
	g++ sender_sockopt.cpp -o sender_sockopt
	g++ receiver_sigalrm.cpp -o receiver_sigalrm
	g++ receiver_sigalrm.cpp -o receiver_select
	g++ receiver_sigalrm.cpp -o receiver_sockopt
